default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PGUSER'] %> # Change to your username
  password: <%= ENV['PGPASSWORD'] %> # variable previously added
  host: <%= ENV['PGHOST'] %>

development:
  <<: *default
  database: event-calendar-development

test:
  <<: *default
  database: event-calendar-test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: event_calendar_BE_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: event_calendar_BE_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: event_calendar_BE_backend_production_cable
    migrations_paths: db/cable_migrate